name: Publish docs to Wiki
# Credit: https://nimblehq.co/blog/create-github-wiki-pull-request
on:
  push:
    paths:
      - 'Asset/**'
      - 'SourceCode/**'
    branches:
      - main

jobs:
  publish_asset_to_wiki:
    name: Publish Asset to Wiki
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.head_commit.changed_files != 0 && contains(github.event.head_commit.modified, 'Asset/')
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Pull wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name ${{ secrets.WIKI_USER_NAME }}
          git config user.email ${{ secrets.WIKI_USER_EMAIL }}
          git pull https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/TheSuperHackers/GeneralsGamePatch.wiki.git

      - name: Push wiki
        run: |
          rsync -av --delete .github/wiki/Asset/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "Update Wiki content"
          git push -f --set-upstream https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/TheSuperHackers/GeneralsGamePatch.wiki.git master

  publish_sourcecode_to_wiki:
    name: Publish SourceCode to Wiki
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.head_commit.changed_files != 0 && contains(github.event.head_commit.modified, 'SourceCode/')
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Pull wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name ${{ secrets.WIKI_USER_NAME }}
          git config user.email ${{ secrets.WIKI_USER_EMAIL }}
          git pull https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/TheSuperHackers/GeneralsGameCode.wiki.git

      - name: Push wiki
        run: |
          rsync -av --delete .github/wiki/SourceCode/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "Update Wiki content"
          git push -f --set-upstream https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/TheSuperHackers/GeneralsGameCode.wiki.git master